### PR TITLE
Added initial untested noise file

### PR DESCRIPTION
**Pull request by k-eato**
Still need to create a test function and verify this works as intended with the data object.

### CODE REVIEW

**Comment by rishigurnani** [comment]
This is awesome progress so far! @k-eato Should we merge before or after you add the test case?

**Comment by rishigurnani** [comment]
@k-eato I added a bitmask function for you to use. Should the mask come before or after the softmax? Probably before, right?

**Comment by rishigurnani** [comment]
Thanks for implementing deletion @SVJayanthi. I'll start implementing the contrastive trainer then. Can you add some test cases for deletion to `test_contrast.py`?

**Comment by rishigurnani** [comment]
@SVJayanthi I believe there is a bug in your implementation. The batch attribute of the `Data` object needs to be set in `delete_node` (e.g., after line 33 of node_deletion.py).

**Comment by rishigurnani** [comment]
Sorry @k-eato @SVJayanthi ! I was clicking another button on my screen which happened to overlap with the "merge" button, leading to chaos. So I went ahead and reverted this PR but now it is closed. Should we open another?

**Comment by k-eato** [comment]
Yeah, I guess we should open another. Sorry for the delayed responses. Yes, it should be before the softmax. I was thinking I make the noise object and I'd multiply it by the mask elementwise, then we can add it and pass through softmax if necessary. That way the values shouldn't be affected by the softmax because t will still be one one and a bunch of zeroes.

**Pull request merged**
